import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// components
import Header from "@/components/Header";
import Feed from "@/components/Feed";
import Modal from "@/components/Modal";
import { useSession } from "next-auth/react";
import { useState, useEffect } from "react";
import {
  addDoc,
  collection,
  getDocs,
  query,
  serverTimestamp,
  where,
} from "firebase/firestore";
import { db2 } from "@/Firebase";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // get details of signed in users
  const { data: session } = useSession();
  const [isSessionSaved, setIsSessionSaved] = useState(false);

  // console.log(session);
  const saveSession = async () => {
    if (session && !isSessionSaved) {
      const usersRef = collection(db2, "signedInUsers");
      const q = query(usersRef, where("name", "==", session.user.name));
      const querySnapshot = await getDocs(q);

      if (querySnapshot.empty) {
        await addDoc(usersRef, {
          name: session.user.name,
          email: session.user.email,
          image: session.user.image,
          time: serverTimestamp(),
        });
        console.log("User added to signedInUsers collection");
        setIsSessionSaved(true);
      } else {
        console.log("User already exists in signedInUsers collection");
        setIsSessionSaved(true);
      }
    }
  };
  useEffect(() => {
    saveSession();
  }, [session]);
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Instagram Clone by Justice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="http://links.papareact.com/jjm" />
      </Head>

      {/* header */}
      <Header />
      {/* feed */}
      <Feed />
      {/* modal */}
      <Modal />
    </div>
  );
}
